[build]
  publish = "report"
  # This command will build the site on Netlify
  command = "pip install -r requirements.txt && jupyter nbconvert --to html --execute --output-dir=report analysis.ipynb --output index.html"

[build.environment]
  PYTHON_VERSION = "3.8"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'"
